name: Daily Auto Run

on:
  schedule:
    - cron: '0 4 * * *' # 北京时间每天中午 12:00 自动运行

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run script
        run: mubu_project.py # 你的代码文件叫 test.py，这里已帮你配好
