name: Daily Auto Run

on:
  workflow_dispatch: # ← 核心：加上这一行，就可以在网页上手动点击运行了！
  schedule:
    - cron: '0 4 * * *' # 北京时间每天中午 12:00 自动运行

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run script
        run: python mubu_project # 运行你的核心文件
